--	USING AVG DAYS TO DELIVER AS A SEPERATE VIEW
SELECT DISTINCT 
                      TOP (100) PERCENT ITEM.ITEM_ID, ITEM.ITEM_NO, RTRIM(REQ.REQ_NO) AS REQ_NO, REQ_ITEM.LINE_NO, ITEM.DESCR, REQ_ITEM.QTY AS PAR, 
                      SUBSTRING(REQ_ITEM.UM_CD, 7, 2) AS [PAR UM], ITEM.CTLG_NO, RIGHT(RTRIM(ITEM_VEND_PKG.UM_CD), 2) 
                      + ' ' + CAST(RIGHT(RTRIM(ITEM_VEND_PKG_FACTOR.TO_QTY), 4) AS VARCHAR) + ' ' + RIGHT(RTRIM(ITEM_VEND_PKG.TO_UM_CD), 2) AS PKG_STR, 
                      CASE WHEN LOC.LOC_TYPE = 1 THEN REQ_ITEM.PAR_BIN_LOC ELSE SLOC_ITEM_BIN.BIN_LOC END AS [BIN LOC], 
                 CASE WHEN (SELECT AVG_DAYS_TO_DELIV FROM vAvgDays2Delv VAD WHERE VAD.ITEM_NO = ITEM.ITEM_NO)  < 1.0 THEN 1.00 
				 ELSE CAST((SELECT AVG_DAYS_TO_DELIV FROM vAvgDays2Delv VAD WHERE VAD.ITEM_NO = ITEM.ITEM_NO) AS decimal(9, 2)) END AS LEAD_DAYS,
				 LOC.LOC_ID,LOC.NAME AS LOC_NAME
    FROM     [h-hemm].dbo.REQ INNER JOIN
                      [h-hemm].dbo.REQ_ITEM ON REQ.REQ_ID = REQ_ITEM.REQ_ID INNER JOIN
                      [h-hemm].dbo.ITEM ON REQ_ITEM.ITEM_ID = ITEM.ITEM_ID LEFT OUTER JOIN
                      [h-hemm].dbo.ITEM_VEND ON ITEM.ITEM_ID = ITEM_VEND.ITEM_ID INNER JOIN
                      [h-hemm].dbo.ITEM_VEND_PKG ON ITEM_VEND.ITEM_VEND_ID = ITEM_VEND_PKG.ITEM_VEND_ID INNER JOIN
                      [h-hemm].dbo.ITEM_VEND_PKG_FACTOR ON ITEM_VEND_PKG.ITEM_VEND_ID = ITEM_VEND_PKG_FACTOR.ITEM_VEND_ID AND 
                      [h-hemm].dbo.ITEM_VEND_PKG.UM_CD = ITEM_VEND_PKG_FACTOR.UM_CD AND 
                      [h-hemm].dbo.ITEM_VEND_PKG.TO_UM_CD = ITEM_VEND_PKG_FACTOR.TO_UM_CD INNER JOIN
                      [h-hemm].dbo.SLOC_ITEM_BIN ON SLOC_ITEM_BIN.ITEM_ID = REQ_ITEM.ITEM_ID INNER JOIN
                      [h-hemm].dbo.LOC ON LOC.LOC_ID = SLOC_ITEM_BIN.LOC_ID 					 
    WHERE  (ITEM.STAT IN (1, 2)) AND (ITEM_VEND.SEQ_NO = 1) AND (ITEM_VEND_PKG.SEQ_NO = 1) AND (REQ.REQ_TYPE = 3) 
	AND (REQ.STAT = 13) AND (REQ_ITEM.QTY > 0) AND 
                      (LOC.INACT_IND = 'N') 
    ORDER BY REQ_NO, REQ_ITEM.LINE_NO


--	USING AVG DAYS TO DELIVER AS A FUNCTION
SELECT DISTINCT 
                      TOP (100) PERCENT ITEM.ITEM_ID, ITEM.ITEM_NO, RTRIM(REQ.REQ_NO) AS REQ_NO, REQ_ITEM.LINE_NO, ITEM.DESCR, REQ_ITEM.QTY AS PAR, 
                      SUBSTRING(REQ_ITEM.UM_CD, 7, 2) AS [PAR UM], ITEM.CTLG_NO, RIGHT(RTRIM(ITEM_VEND_PKG.UM_CD), 2) 
                      + ' ' + CAST(RIGHT(RTRIM(ITEM_VEND_PKG_FACTOR.TO_QTY), 4) AS VARCHAR) + ' ' + RIGHT(RTRIM(ITEM_VEND_PKG.TO_UM_CD), 2) AS PKG_STR, 
                      CASE WHEN LOC.LOC_TYPE = 1 THEN REQ_ITEM.PAR_BIN_LOC ELSE SLOC_ITEM_BIN.BIN_LOC END AS [BIN LOC], 
                 CASE WHEN (SELECT dbo.fn_AvgDays2Delv(ITEM.ITEM_NO)) < 1.0 THEN 1.00 
				 ELSE CAST((SELECT dbo.fn_AvgDays2Delv(ITEM.ITEM_NO)) AS decimal(9, 2)) END AS LEAD_DAYS,
				 LOC.LOC_ID,LOC.NAME AS LOC_NAME
-->>>			.....THE REST IS THE SAME AS ABOVE.....

--	AVG DAYS TO DELIVER FUNCTION
FUNCTION [dbo].[fn_AvgDays2Delv] 
(
	@itemNo CHAR(15)
)
RETURNS FLOAT
AS
BEGIN
	DECLARE @AVG_DAYS_TO_DELIV FLOAT

	SELECT @AVG_DAYS_TO_DELIV = AVG(CONVERT(float, DATEDIFF(day, PO.PO_DATE, PL.LAST_RCV_DATE))) 
	FROM      [h-hemm].[dbo].PO INNER JOIN
					[h-hemm].dbo.PO_LINE AS PL ON PO.PO_ID = PL.PO_ID INNER JOIN
					[h-hemm].dbo.ITEM AS I ON PL.ITEM_ID = I.ITEM_ID INNER JOIN
					[h-hemm].dbo.PO_SUB_LINE AS PSL ON PL.PO_LINE_ID = PSL.PO_LINE_ID INNER JOIN
					[h-hemm].dbo.CC ON PSL.CC_ID = CC.CC_ID
	WHERE   (PL.STAT IN (3, 10)) AND (LEFT(I.ITEM_NO, 2) <> '~[') AND (PO.PO_DATE BETWEEN DATEADD(day, - 365,
                    (SELECT GETDATE() AS Expr1)) AND DATEADD(ms, - 3, DATEADD(day, 1,
                    (SELECT GETDATE() AS Expr1))))
	RETURN @AVG_DAYS_TO_DELIV
END